apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nadheeshwaran
  namespace: nadheesh
  labels:
    app: nadheeshwaran
spec:
  replicas: 2

  selector:
    matchLabels:
      app: nadheeshwaran
  template:
    metadata:
      labels:
        app: nadheeshwaran
    spec:
      containers:
      - name: nadheeshwaran
        image: kbrajeshwaran/rishi:v.0.0
        ports:
        - containerPort: 80