apiVersion: v1
kind: Service
metadata:
  name: my-nadheeshwaran-svc
  namespace: nadhees
  labels:
    app: nadheeshwaran
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  selector:
    app: nadheeshwaran